msFilterList
# Updated: 21 September 2013 (11:31:18 AM)
: Expires=3
#
# Homepage:  http://adversity.uk.to/
#
# Title: Antisocial
#
#
# License: http://creativecommons.org/licenses/by/3.0/
#
# This list blocks the ever increasing social networking content on third-party sites.
#
- (facebookLike,
- -delicious-24x24.
- -digg-icon.
- -facebook-64.
- -facebook-grey.
- -facebook-icn-
- -facebook-icon.
- -facebook-like.
- -facebook-promo.
- -facebook-share-
- -facebook-share.
- -Facebook_ico.
- -facebook_icon.
- -facebookBig.
- -fb-follow.
- -FB-MOdule_
- -follow-facebook.
- -follow-youtube.
- -footer-facebook-
- -footer-facebook.
- -footer-share-links.
- -footer-tweeter-
# -Google-Plus.$image
- -Google-Plus_ico.
# -GooglePlus-$image
- -gplus-banner.
# -gplus.$image
- -gplus22x22.
- -icon-facebook.
- -icon-youtube.
- -icons-facebook.
# -icons-youtube.$domain=~youtube.com
- -nudge-fb.
- -on-facebook.
- -on-twitter-
# -opensocial.googleusercontent.com^$domain=~google.co.nz|~google.ca|~google.co.uk|~google.com|~google.com.au|~youtube.com
- -share-digg.
- -share-fb-bubble.
- -share-fb.
- -share-icons-
- -share-icons.
- -share-reddit.
- -share-sprite24x24.
- -share-su.
- -sharing-facebook.
- -small-facebook.
- -social-buttons/
- -Social-Count-
- -social-fb.
- -social-icons-
- -social-icons.
- -social-share-buttons/
- -social-slider/
- -social-sprite.
- -social-twitter-icon.
- -SocialIcon1.
- -SocialIcon2.
- -SocialIcon3.
- -socialise/plugins/
# -tweet.$image,domain=~news.com.au
- -twheet-bubble-
- -twitter-button-
- -twitter-fan.
- -twitter14.
- -twitter22x22.
- -Twitter_ico_
- -twittertool-icon.
- -YouTube_ico.
# .com/digg.$domain=~digg.com
- .com/fb.jpg
- .com/i/fb.
- .newsSocialBar.
- .social-icons.
- /+1/messageproxy?gcv=
- /16x16-delicious.
- /16x16-digg-
- /16x16-reddit.
- /195x25_Facebook.
- /195x25_Twitter.
# /220x90.$domain=hardwareheaven.com
- /32/digg.
- /ad_rbtwitter.
- /add-to-any-
# /addthis.$domain=~skycomp.com.au|~whatsmyip.org
- /addthis/icons/
- /addthis32x32/
- /addthis48.
- /addthis_share.
- /addthis_sprite.
# /addthis_widget.$domain=~iamsecond.com
- /addThisButton.
- /AddTo_Delicious.
- /AddTo_Digg.
- /AddTo_Furl.
- /AddTo_Google.
- /AddTo_Live.
- /AddTo_MrWong.
- /AddTo_Newsvine.
- /AddTo_Reddit.
- /AddTo_stumbleupon.
- /AddTo_Technorati.
- /AddTo_Yahoo.
- /addtomyyahoo4.
- /anmiated-twitter-bird/
- /app-iphone.
# /app_facebook.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /app_twitter.
- /apple_32.
- /apple_32_
- /art/socialbutton_
- /art_buttons_spirite.
- /articleShare.
- /assets/*-facebook.
- /banner-share.
- /banner/*facebook.
- /banner/followus/
- /Banners/Face_Book.
- /banners/facebook.
# /banners/youtube.$image,domain=~youtube.com
- /base/followbar.
- /beknown_icon.
- /bgHeaderTwitter.
- /bgSocialMedia.
- /big-facebook.
- /bkmk_delicious.
- /bkmk_digg.
- /bkmk_google.
- /bkmk_stumbleupon.
- /blogger_button_
- /blogs/facebook.
- /blogSocialMedia.
- /book-del.
- /book-furl.
- /bookmark/*digg.
# /bookmark/*facebook.$domain=~facebook.com|~fbcdn.net
- /bookmark/*share.
- /bookmarkcraze_
- /bookmarks/digg.
- /bookmarks/facebook.
# /bookmarks/google.$image
- /bookmarks/mr-wong.
- /bookmarks/myspace.
- /bookmarks/stumble-
# /bookmarks/yahoo.$image
- /bookmarksite_delicious.
- /bookmarksite_digg.
- /bookmarksite_facebook.
- /bookmarksite_google.
- /bookmarksite_myspace.
- /bookmarksite_stumbleupon.
- /bookmarksite_technorati.
- /bot_social.
- /bt_facebook.
- /bt_twitter.
- /btn-facebook.
- /btn-fb.
- /btn-myspace.
- /btn-youtube.
# /btn_f.$image
- /btn_facebook.
- /btn_facebook_
- /btn_FB.
- /btn_follow_
- /btn_foursquare_
- /btn_in.gif
- /btn_mySpace.
- /btn_retweet.
- /btn_su_
# /btn_t.$image
- /btn_twitter.
- /btn_youtube.
- /btn_youtube_
- /btnShareOff.
- /btnShareOn.
- /but_facebook.
- /but_twitter.
- /button-facebook-
- /Button-Scoopit-
- /button-share-gray.
- /button-share.
- /button-twitter-
- /Button-YouTube.
- /button1-bm.
- /button_fb.
- /button_myspace.
- /button_small_sharethis.
- /Buttons-Facebook.
- /buttons-like.
- /Buttons-Linkedin.
- /Buttons-Twitter.
# /buttons/*youtube.$image
- /buttons/digg.
- /buttons/facebook.
- /buttons/facebooklogin.
- /buttons/social_services.
- /Chrome-Facebook-
- /Chrome-Twitter-
- /commentshareicons.
- /communitylogos/facebook.
- /communitylogos/youtube.
# /connect-facebook.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /connect-icons/facebook.
- /connect_facebook.
# /connect_facebook_$domain=~facebook.com|~fbcdn.net
- /connect_sprite.
- /connectSprite2.
- /dd-facebook.
- /del.icio.
- /del_link.
- /delicious-16x16.
- /Delicious-24x24.
# /delicious-bookmarks$~xmlhttprequest
- /delicious-ico.
- /delicious-icon
# /delicious.$domain=~delicious.com
- /delicious2.
- /delicious48.
- /delicious_
- /delicouslogo.
- /dfg_fb.
# /dfg_google.$image
- /dfg_tw.
# /digg-$~stylesheet,domain=~digg.com|~venturebeat.com
# /digg.$~stylesheet,domain=~digg.com
- /digg48.
- /Digg_16x16.
- /digg_32.
- /digg_32x32.
- /Digg_48x48.
- /digg_icon.
- /digg_img
- /diggcompact.
- /diggfollow.
# /diggIcon.$~object-subrequest
- /digglogo.
- /diggman.
- /dolWebAnalytics.
# /etc/fb.$image
- /extras/facebook/
- /Facbook_icon.
- /facbook_icon_
- /face-icon.
- /facebook+24x24.
# /facebook-$domain=aussiedisposals.com.au
- /facebook-128x128.
- /facebook-20x20.
- /facebook-24x24.
- /facebook-32.
- /facebook-32x32.
- /facebook-35x35.
- /facebook-64x64.
- /facebook-banner-
- /facebook-bt.
- /facebook-button-48x48.
- /Facebook-Button.
- /Facebook-Buttons-
- /Facebook-grey-background.
- /facebook-icon
- /facebook-linkedin-
- /facebook-logo-
- /facebook-logo.
- /facebook-menu-button.
- /facebook-share-
- /Facebook-Small.
- /facebook-tb.
- /facebook-top.
- /facebook.ashx?imgver=
- /facebook/32x32.
- /facebook/32x32.
- /facebook/icon.
# /facebook1.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /facebook123.
- /facebook16x14.
- /facebook16x16.
- /facebook20.
- /facebook22./facebook24px.
- /facebook24x24.
# /facebook32.$domain=~facebook.com|~fbcdn.net
- /facebook48.
# /facebook_$~stylesheet,domain=~arstechnica.com|~mlb.com|~slashdot.org|~forumisapro.com|~freemyapps.zendesk.com|~theverge.com
- /facebook_24.
- /facebook_button.
- /facebookbutton.
- /facebookbuttong.
- /facebookcomment.
- /FacebookFanWidgetFrame.
- /FacebookGroup.
- /FacebookIcon-
# /facebookicon.$~object-subrequest
- /facebookIcon12_
- /FacebookIcon3.
- /facebookjb.
- /facebookLarge.
- /facebooklink.
- /facebookListens.
- /facebookLocal.
# /facebooks.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /facebookslide.
- /facebookv.
- /facebutton.
- /FarkItButton2_16x16.
- /favicons/facebook.
- /fb-32x32.
- /fb-campaign.
- /fb-comment-button.
- /fb-connect.
- /fb-header-logo.
- /fb-icon.
- /fb-like-box-
- /fb-like.
- /fb-link.
- /fb-mini.
- /fb-open-graph-
- /fb-recommend-icon
- /fb-share-
- /fb-share.
- /fb-sky-
- /fb-square.
- /fb.png?
- /fb/js/recommend.
- /fb12.
- /fb_16x16.
- /fb_base_
- /fb_bg2.
- /fb_btn.
- /fb_button_sprite.
- /fb_connect.
- /fb_connect2.
- /fb_icn.
- /fb_ico.
- /fb_icon.
- /fb_icon_
# /fb_logo.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /fb_middle.
- /fb_mini.
- /fb_share.
- /fb_share_
- /fb_small.
- /FB_TT_Buttons/
- /FBActive2.
# /fbconnect/*$~stylesheet,domain=~facebook.com|~fbcdn.net
# /fbConnect_$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /fbIcon.
- /fblike.
- /fblikebutton2.
- /fblogo.
- /fbservices.
# /fbshare.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /fbSmall.
- /fbtwrss.
- /feedbuttons/
- /findusfacebook.
- /fl_box.php?
- /flickr_icon.
- /flock_btn.
- /follow-button.
- /follow-icon-
- /follow-icons.
- /follow-me-on-twitter.
- /follow-me/images/googleplus.
- /follow-ram-module_
- /follow-sprite.
- /follow-tab-buttons.
- /follow-us-icons.
- /follow-us-on-
- /follow-us.
- /follow-us_
- /follow-youtube.
- /follow/*digg.
- /follow/Facebook-
- /follow_bird_
- /follow_button.
- /follow_buttons/
- /follow_googleplus_
- /follow_me-
- /Follow_Me.
- /follow_sprite.
- /follow_twitter.
- /follow_us
- /follow_youtube_
- /followme.
- /FollowmeTwitter.
- /followtwitter2.
- /followus.
- /followusfb.
- /followusontwitterbird.
- /followussmall.
- /followustweeter.
- /followustwittersmall.
- /foot-fb.
- /foot-twit.
- /foot-youtube.
- /footer-facebook.
- /footer-social-links/
# /footer-social.$domain=~affiliates.mozilla.org
- /footer-youtube.
- /footer/fb.
- /footer/social/
- /footer/tw.
- /footer_facebook
- /footer_fb.
- /footer_nav_fb.
- /footer_nav_tw.
- /footer_tw.
- /footer_twitter
- /footer_youtube_
- /forum/digg.
- /forum/google_sm.
- /friendconnect.
- /friends-connect.
- /fshare.
- /ftr_facebook.
- /ftr_twitter.
- /furl.
- /gbuzz.
- /getclickybadge.
- /GetSprite.ashx?path=
- /gfxShareThis.
- /gfxTwitter.
- /gl_social.
- /global/social.
- /Google+.
# /google-24x24.$image
- /Google-Plus-grey-background.
- /google-plus-icon.
- /google-plus-logo.
- /google-plus-pages-logo.
- /google-plusv.
- /google-reader-
- /google-tb.
- /google_plus-icon.
# /google_plus.$domain=~googlezeitgeist.com
- /google_plus_logo_
- /google_twitter.js
# /googlebookmark.$image
- /googleplus-bt.
# /googleplus.$image
- /googleplus.
- /googleplus.jpg
- /googleplus/32x32.
- /googlePlus1.
- /googlePlus24x24.
- /GooglePlus32.
- /googleplus_
- /googleplusalt.
- /gplus-16.
- /gplus-32.
- /gplus-icon-
# /gplus.$image
- /gplus.gif
- /gplus12.
- /gplus2.
- /gplus_
- /gplusrp.
- /gprofile_button-
- /headBtnFacebook.
- /header-facebook.
- /header_nav_fb.
- /header_nav_tw.
- /header_twitter.
- /headSprite.gif?
# /highlights/facebook.$domain=~facebook.com|~fbcdn.net
- /Home-Share-
- /homeFacebook.
- /homeTwitter.
- /hoton_sprite.
- /hp-Facebook.
- /hp-myspace.
- /ic/fb2.
- /ic/twitt2.
- /ic/youtube.
- /ic/youtube2.
- /icn-fb.
- /icn-fk.
- /icn-tw.
- /icn-ut.
- /icn_fb_
- /icn_googe_plus.
- /icnFacebook.
- /icnTwitter.
- /ico-delicious.
- /ico-digg-
- /ico-digg.
- /ico-facebook-
- /ico-facebook.
- /ico-FB-
- /ico-fb.
- /ico-reddit.
- /ico-social-
- /ico-stumble.
- /ico-stumbleupon.
- /ico-subscribe-social.
# /ico-tw.$image
- /ico-twit.
- /ico-YouTube-
- /ico-youtube.
- /ico/twitteri.
- /ico_del.
- /ico_delicious.
- /ico_Facebook.
- /ico_facebook_
- /ico_fb_
- /ico_flickr.
- /ico_google.
- /ico_live.
- /ico_newsvine.
- /ico_Plurk.
- /ico_share_btns.
- /ico_slashdot.
- /ico_stumble.
- /ico_technorati.
- /ico_tw_
- /ico_Twitter.
- /ico_vimeo.
- /ico_yahoo.
- /icoDigg.
- /icon-delicious.
- /icon-digg
# /icon-facebook$domain=~myfav.es
- /icon-fark.
- /icon-fb-
- /icon-fb.
- /icon-google.
- /icon-googleplus.
- /icon-itunes-
- /icon-itunes.
- /icon-linkedin.
- /Icon-MySpace-
- /icon-share-facebook.
- /icon-share.
- /icon-social-
- /icon-social.
- /icon-sprite-share.
- /icon-stumble.
- /icon-stumbleupon
- /icon-tw.
# /icon-twitter$domain=~myfav.es
- /icon-you-tube.
- /icon-youtube-
- /icon-youtube.
- /icon.youtube.
- /icon/digg_
- /icon/fb.
- /icon/reddit_
- /icon_addthis.
- /icon_delicious.
- /icon_delicious_
- /icon_delicous.
- /icon_digg.
- /icon_facebook.
- /icon_facebook_
- /icon_fb.
- /icon_fb_16x16.
- /icon_feedburner_
- /icon_follow_sp-sprite.
- /icon_furl.
- /icon_gplus_32.
- /icon_myspace.
- /icon_reddit.
- /icon_sb_
- /icon_share.
- /icon_share_
- /icon_social_long.
- /icon_stalk_facebook
- /icon_stalk_twitter
- /icon_stumbleupon.
- /icon_su.
- /icon_tweeter.
- /icon_twitter
- /icon_youtube.
- /icon_youtube_
- /icone-fb.
- /iconFacebook.
- /iconFacebook_12x12.
- /iconFB24.
- /icons-follow-
- /icons-social-bar.
- /icons/*-social-media.
- /icons/*_social_profiles.
- /icons/button-stoke-
- /icons/deliciousd.
- /icons/digg.
- /icons/diggd.
- /icons/facebook.
# /icons/facebook/*$domain=~facebook.com|~fbcdn.net
- /icons/facebooklogo.
# /icons/fb.$image
- /icons/fb_
- /icons/feature/sprite_mail_hp.
- /icons/google/google_
- /icons/itunes_
- /icons/linkedin-
- /icons/myspace-
- /icons/redditd.
- /icons/share.
- /icons/social-media.
- /icons/socialize/
- /icons/socialnetworks/
- /icons/sprShare.
- /Icons/Squidoo.
- /icons/stumbleupond.
- /icons/twtr.
- /icons/youtube.
- /icons/yt_
- /icons_social_
- /iconTW24.
- /iconTwitter.
- /iconTwitter_12x12.
- /icoSocialBar.
- /iframe_follow_
- /igFacebook.
- /igTwitter.
- /im/social.
# /images/*-twitter-$domain=~ibtimes.com|~news.com.au
- /images/*_facebook.
- /images/*_twitter.
- /images/adigg.
- /images/bg-share-btns.
- /images/button_share.
- /images/digg.
- /Images/digg_
# /images/facebook$domain=redmondpie.com
# /images/facebook.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /images/facebook2.
- /images/facebook22x22.
- /images/facebook32x32.
- /images/facebookb.
- /images/facebookonly
- /images/fb.
- /images/follow-fb.
- /images/frame-fb.
- /images/frame-twitter.
- /images/g+.
- /images/ic/fb.
- /images/icon_stumbleit.
- /images/linkedin2.
# /images/myspace.$domain=~myspace.com
# /images/myspace_$domain=~myspace.com
- /images/pinterest.
- /Images/reddit_
- /images/share_social
- /images/sn_face_book.
- /images/sn_tweeter.
- /images/sociable/
# /images/social-$domain=~raymond.cc
- /images/social/social.
- /images/social_icons
- /images/social_network/
- /images/socialbar/
- /images/socialicons/
- /images/socialnet/
- /images/socialsm.
- /images/sprite-images.
- /images/sprite_subscribe_
# /images/stumble.$domain=~stumbleupon.com
- /images/stumbleit.
- /images/StumbleThru.
- /images/twit.
# /images/twitter$domain=~grahambird.co.uk|~mashable.com|~twitter.com|~twitvid.com|~freemyapps.zendesk.com
- /images/widget_FollowUs.
- /img/digg.
# /img/facebook.$domain=~facebook.com|~fbcdn.net|~ghsrv.com|~linkedin.com|~twitter.com
- /img/fark.
- /img/fb2.
- /img/flickr.
- /img/ico-face.
- /img/itunes_icon.
- /img/share/button.
- /img/SharingBadge
- /img/social/
- /img/tweet.
- /img/twitt2.
- /img/yahoomyweb.
# /img/YouTube.$domain=~youtube.com
- /imgs/digg.
- /imgs/facebook.
- /in-share.
- /infobar-social.
- /instagram-bt.
- /interactive/delico.
- /interactive/digg.
- /interactive/facebook.
# /interactive/google.$image
# /interactive/newsvine.$image
- /interactive/stumble.
# /interactive/youtube.$image
- /joinTwitter.
- /js/diggthis.
- /js/social.js?v=
# /kakinetwork.js$domain=pakfunplace.com
- /kickstarter-bt.
# /klout.$image,third-party
- /large-sprite5.
- /ldigg.
- /li-icon.
- /lifehack-*/social
- /like.php?
- /like_sprite_
- /like_us.
- /likebox.php?
- /likeus.
- /link-delicious.
- /link-digg.
- /link-facebook.
- /link-icon-sprite.
- /link-myspace.
- /link_facebook
- /link_twitter
- /linked-in-
- /linked-tb.
- /linked_icon.
- /linkedin-32x32
- /linkedin-dark.
- /linkedin-icon
- /linkedin-sml.
# /linkedin.$domain=~cnet.com|~linkedin.com|~makeuseof.com
- /linkedin/32x32.
- /linkedin75.
- /linkedin_24x24.
- /LinkedIn_32.
- /linkedin_36x36.
- /linkedin_48px.
- /linkedin_social.
- /LinkedInIcon.
- /LinkedInLander.
- /linkin_share.
- /Live_Messenger_32.
- /logo-facebook.
- /logo_facebook
- /logo_fb_36.
- /logo_tw_36.
- /logo_twitter
- /logoFB.
- /logoTwit.
- /media/followus_
# /media/social/*$image
# /media/socials.$image
# /MediumYoutube.$image
- /mega_like.
- /metacriticButton.
- /mini_stumble.
- /misc/facebook.
# /misc/myspace.$image
# /misc/stumble.$image
- /modules/twittertool.
- /msdntwitter.
- /mwmac.
- /MySpace-24x24.
- /myspace-icon.
- /myspace_30.
- /MySpace_48x48.
- /myspaceid.
- /nav-facebook.
- /Nest/facebook
- /Nest/twitter
- /nimages/facebook.
- /p1sprite.
- /pics/twitter
- /Pinterest-icon.
- /playlist-hangout-icon-
- /plugins/fan.php?id=
- /plugins/socialize-
- /plusone/?url=
- /png_digg
- /png_twitter
# /post_to.$image
- /RA/facebook.
- /reddit-20x16.
- /reddit-bookmark
- /reddit-favicon_
- /reddit-ico.
- /reddit-icon
# /reddit.$domain=~makeuseof.com|~reddit.com
- /reddit2.
- /reddit48.
- /reddit_32x32.
- /reddit_icon.
- /rss_mymsn.
- /rss_twitter.
- /sb_facebook2.
- /sb_icons/facebook.
- /sb_icons/myspace.
- /sb_twitter.
- /sc_facebook.
- /sc_twitter.
# /sc_youtube.$domain=~youtube.com
# /ScoailMedia_$image
# /sexybookmarks/*$~stylesheet
- /sh_delic.
- /sh_digg.
- /sh_facebook.
- /sh_twitter.
- /share-and-follow/
# /share-btn.$~stylesheet
- /share-buttons.
- /share-delicious.
- /share-digg.
- /share-facebook.
- /share-icon-
- /share-icons-
- /share-icons.
- /share-icons/
- /share-links-
- /share-logos.
- /share-on-facebook-
- /share-page-
- /share-reddit.
- /share-sprites.
- /share-stumble.
- /share-this.gif
- /share-this/digg.
- /share-twit.
- /share-widget-buttons.
- /share/digg.
- /share/face.
- /share/facebook.
- /share/fark.
- /share/icon.
- /share/myspace-
- /share/reddit_
- /share/share_btn.
- /share/shareicons
- /share/stumble.
- /share/stumbleupon-
- /share/twit.
- /share42.
- /share_64x21.
# /share_bar.$~stylesheet
- /share_button.
# /share_buttons.$domain=~xkcd.com
- /share_digg-
- /share_digg.
- /share_drop24.
- /share_facebook.
- /share_fb.
- /share_fb_
- /share_icon_
- /share_icons.
- /share_icons/
- /share_icons_smaller.
- /share_it_facebook.
- /share_reddit-
- /share_reddit.
- /share_save_
- /share_sprite.
# /share_sprite_$domain=~babycenter.com
- /share_stumble.
- /share_stumbleupon
- /share_tw.
- /share_twitter
- /shareBar-
- /sharebar_
# /shareBebo.$image
- /shareDigg.
- /shareFacebook.
- /shareFacebook_
- /shareIcons.
- /sharelinks/buzz.
- /sharelinks/digg.
- /sharelinks/facebook.
- /sharelinks/stumble.
- /sharesites.
- /shareSprite_
- /ShareThis/
- /sharethisentry.
- /shareTwitter.
- /shareTwitter_
- /sharing_bottom_sprites.
- /sharing_tools_
- /sharingIcons.
- /sidebox_subscribe_fb.
- /sidebox_subscribe_twt.
- /sidetab-facebook.
- /sign-in-with-twitter
- /silverstone-facebook-
- /simple-social-icons/
- /site/bug_facebook.
- /site/bug_twitter.
- /site/lfacebook.
- /site/reddit_
- /site/sharethis.
- /Skype_32.
- /slashdot-16x16.
- /slightlybiggerfacebook.
- /sm/digg.
- /sm/facebook.
- /smalllogos/facebook.
- /smalllogos/youtube.
- /smallpics/facebook.
- /sn-icons.
- /sociable.js
- /sociable/images/
- /sociables/digg.
- /sociables/facebook.
- /social-big-
# /social-buttons.$domain=~newyorkjets.com
- /social-cnt-
- /social-facebook.
- /social-icon-
- /social-icons-
- /social-icons.
- /social-links/
- /social-media-icons-
- /social-media-sprite
# /social-media-widget/*$~stylesheet
- /social-media.png?
- /social-mod/facebook.
- /social-network-sprite.
- /social-networks/myspace.
# /social-share.$domain=~weather.com
# /social-sprite.$domain=~thecarconnection.com
- /social-subscribe-bg
- /social-youtube.
# /social.$domain=mmt.com.au|shrib.com
- /social.php?
- /social.png?
- /social/bebo.
# /social/blogger.$image
- /social/digg.
- /social/digg_
# /social/facebook.$image
- /social/fb.
- /social/fb_
- /social/follow-
- /social/friendfeed.
# /social/google.$image
- /social/googleplus.
- /social/itunes.
# /social/live.$image
- /social/mfacebook.
- /social/mtwitter.
- /social/myoutube.
- /social/myspace.
- /social/myspace_
- /social/newsvine.
- /social/reddit_
- /social/retweet-
- /social/share_
- /social/shareit.
- /social/sharethis.
- /social/snwicons_
- /social/sprite.
- /social/technorati_
- /social/tw.
- /social/tweeter_
- /social/twit_
# /social/virb.$image
- /social/youtube-
- /social2.
- /social?blog=
- /social?link=
- /social_buttons.
# /social_buttons/*$domain=~yahoo.com
- /social_chicklets.
- /social_f.
- /Social_Facebook.
- /social_fb
- /social_feedback.
- /social_feedback_
- /social_footer.
- /social_icon/digg.
- /social_icon/facebook.
- /social_icons.
- /social_icons/
- /Social_Icons_
- /social_link.
- /Social_links/
- /social_m.
- /social_masthead_
- /social_media.
# /social_media/*$domain=~socialblogsitewebdesign.com
- /Social_Nav_
- /social_network_logos.
- /social_networking_iconpack/
- /social_networks/
- /social_popup.
- /social_sprite.
- /social_stats.
# /social_subscribe_$image
- /social_t.
- /social_twitter.
- /social_v5.
- /social_youtube.
- /socialbadges.
- /socialbar-*.js
- /socialbar-icons.
- /socialBar.
- /socialbookmark_
- /socialbookmarking/
- /SocialBookmarkManager.js
- /socialbookmarks/
- /socialbookmarks01.
- /socialbot.
- /socialicons.
- /socialicons/facebook.
- /socialicons2.
- /socialicons_
- /socialize-icons.
# /socialize.js?apiKey=$domain=~nydailynews.com|~goal.com
# /socialmedia-$image
# /socialmedia.$image
# /socialmedia/*$domain=~forums.adobe.com|~thenextweb.com
- /SocialMedia16x16.
# /socialmedia_$image
- /SocialMediaFacebook_
- /SocialMediaIcons/
- /SocialMediaTwitter_
- /SocialMediaYoutube_
- /socialnet/facebook.
- /socialnet/icons/
# /SocialNetworking/*$image
- /socialnetworking/*digg.
- /socialnetworking/*facebook.
- /socialnetworking/*furl.
- /socialnetworking/*myspace.
- /socialnetworkingbuttons/
- /socialnetworks/facebook.
- /socialnetworks/share_
- /socialPromote.
- /socialround.
- /socialShare.
- /socialShareFB-
- /socialshareprivacy.
# /socialshareprivacy/*$domain=~googleusercontent.com
- /socialShareTwitter-
- /SocialSprite.
- /socialsprites.
- /SocialTiles.
- /SocialWeb/ico_
# /SocNet_$image
- /spr_share_
- /spread/digg.
- /spread/yahoomyweb.
- /spreadus_button_
- /sprite-main-min.
- /sprite-social_icons.
- /sprite/socialIcons-
- /sprite/sprites.
- /sprite_*_follow_
- /sprite_soc_btn.
- /sprites/share.png?
- /sprites/social-media.
- /stage_twitter.
- /stumble-bookmark
- /stumble-button-
- /stumble-icon
- /stumble-lg.
- /stumble-upon-24x24.
- /stumble-upon-ico.
- /stumble4.
- /stumble_16x16
- /stumble_icon.
- /stumble_link.
- /stumble_upon_
- /stumbleupon-16x16.
- /stumbleupon-bt.
# /stumbleupon.$domain=~makeuseof.com|~stumbleupon.com
# /stumbleupon1.$domain=~stumbleupon.com
- /stumbleupon32.
- /stumbleupon48.
# /stumbleupon_$domain=~stumbleupon.com
- /stumbleUponBadge.
- /su-icon.
- /sub_facebook-
- /sub_facebook.
- /sub_twitter
- /subscribe-google.
- /subscribe_facebook.
- /subscribe_gplus_
- /subscribe_twitter4.
- /syndication-facebook.
- /takeover/Facebook/
- /techcrank_follow.
# /Technorati-$image
- /technorati.
- /technorati48.
- /templates/facebook.
- /templates/facebook/
- /toolbar/fb.
- /toolbar/tw.
- /toolbarIcon_sharePreview.
- /toolbox_like.
- /top_fb.
- /top_social.
- /top_social_
- /top_twitter.
- /tumblr-bt.
- /Tumblr-icon.
# /tumblr.$domain=~makeuseof.com|~tumblr.com|~xkcd.com
- /tumblr0.
- /tumblr_20x20.
- /tumblr_icon.
- /tw-icon.
- /tw-sharing.
- /tw_icon.
- /tweet-button.
- /tweet-head.
- /tweet-this.
- /tweet-this/
- /tweet.png
- /tweet/icon.
- /tweet_button.
- /Tweet_This_
# /tweetit-$domain=~tcmag.com
# /tweetmeme.$domain=~tweetmeme.com
- /tweetmeme/
- /tweetn.
- /tweetquote.
- /tweIcon.
- /twicon.
# /twiitericon.$domain=~twitter.com
- /twit-icon.
- /twit.png?
- /twit1.
- /twit2.
- /twit_icon.
- /twitAd.
- /twiter-icon.
- /twiterfirstrow.
- /twitface_
- /TWITR3.
- /twitt.
- /twittbutton.
- /twitter-20x20.
- /twitter-dark.
- /twitter-icon.
# /twitter.$~stylesheet,domain=~cnet.com|~eff.org|~makeuseof.com|~twitter.com|~twitter.yfrog.com|~wwe.com|~startpins.com|~twitter.github.com|~duckduckgo.com
- /twitter/32x32.
- /twitter/icon.
# /twitter1.$domain=~twitter.com|~venturebeat.com
- /twitter2.
- /twitter24px.
- /twitter24x24.
- /twitter32.
- /twitter3gif.
- /twitter75.
# /twitter_$domain=~engadget.com|~twitter.com|~webdesignerdepot.com|~freemyapps.zendesk.com
- /twitter_button.
# /twitterb.$domain=~twitter.com
- /TwitterBird_
- /twitterbutton.
- /twitterfollow.
- /TwitterIcon-
# /twittericon.$~object-subrequest
- /twittericon48x48.
# /twitterlogo.$domain=~twitter.com
- /twitterNav.
- /twitterPicThumb.
# /twitters.$domain=~twitter.com
- /twitterShareButton.
- /twitterslide.
- /twitterSmall.
- /twittertweeter.
# /twitterwidget?$domain=~twitter.com
- /twitterzm.
- /twitthis.
- /twlogo.
- /twt_base.
- /twt_middle.
# /ui/share.$image
- /v2/digg.
# /wp-content/*/socialize/*$~stylesheet
- /wp-content/*youtube2.
- /wp-content/plugins/*delicious
# /wp-content/plugins/*digg$~stylesheet,domain=~animaltales.info|~rockpapershotgun.com
- /wp-content/plugins/*stumble
- /wp-content/plugins/add-to-any/
- /wp-content/*FaceBook.
- /wp_followme.
- /yahoo_sm_blk.
- /you_tube_icon.
# /you_tube_logo.$domain=~youtube.com
- /youtube-64x64.
- /youtube-bt.
- /youtube-footer.
- /YouTube-grey-background.
# /youtube-icon.$domain=~youtube.com
# /youtube-left.$domain=~youtube.com
- /youtube-logo-
# /Youtube.png$domain=~google.com|~makeuseof.com|~youtube.com
# /youtube23x23.$image
- /youtube24x24.
# /youtube_$domain=aussiedisposals.com.au
- /youtubeButton.
- /youtubeinitial.
- /youtubev.
- =_twitter/
- =facebook_glamorous,
# @@||addthis.com^$domain=knowyourmeme.com|parade.com
+d astuce-facebook.com /style.css
# @@||gigya.com/js/socialize.js$domain=davidguetta.com|forbes.com|nfl.com
# @@||platform.linkedin.com/in.js$domain=businessinsider.com
# @@||yimg.com^*/contact/card-$script,domain=mail.yahoo.com
- _BioIcons-Google.
- _btn_facebook.
- _btn_Share.
- _btn_twitter.
# _button_fb_$image
- _facebook14.
- _facebook20x20.
- _facebook48.
# _facebook_$image,domain=~arstechnica.com|~yahoo.com
- _facebook_16x16.
- _facebook_btn.
- _facebook_f_35x35.
- _facebook_icon
- _facebook_logo.
- _facebookbadge.
- _facebookpromo.
- _fb_banner.
- _fb_button.
- _FB_icon.
# _fbconnect.$domain=~marieclaire.com|~mlb.mlb.com
- _fbook_22x22.
- _flickr_logo.
- _footer_facebook.
- _FShare.
- _google_plus48.
- _icon_digg.
- _icon_Facebook.
- _icon_facebook_
- _icon_fb.
- _icon_su.
- _icon_technorati_
- _icon_Twitter.
- _iconsspriteNew.
- _like_this_and_1_plus.
- _linkedin.
- _logo_social.
- _on_twitter.
- _retweet_all_btn.
- _share_digg.
- _share_facebook.
- _share_icons.
- _share_icons/
- _share_reddit.
- _share_stumble.
- _Share_this_page.
- _share_twitter.
- _share_yahoo.
- _sharing_icons/
# _socailMedia_$image
- _social/icons.
- _social_facebook.
- _social_facebook_
- _social_icons.
# _social_media_ad$image
- _social_shares.
- _social_sprite.
- _social_tracking_
- _social_twitter.
- _socialbookmarks_
- _socialmedia.
- _SocialSprite.
- _toolbar_sprite_
- _toolbox/digg.
- _toolbox/facebook.
- _toolbox/stumbleit.
- _TweetAndTrack.js?
- _twitter20x20.
# _twitter_$~script,~subdocument,~xmlhttprequest,domain=~engadget.com|~index.hr|~twitter.com
- facebook-16x16.
- facebook-32x32s.
- facebook_small.
- followus-facebook.
- gplus_16x16.
- icons/gplus-
- linkedin-16x16.
- linkedin_16x16.
- soc_link_fb.
- twitter&widget_id=
# ||1up.com/media?id=*&type=sm$image
-d addthis.com
-d assets.pinterest.com
# ||assets.tumblr.com^$script,subdocument,third-party
-d aussiedisposals.com.au /twister
-d badge.empireavenue.com .js
-d badge.facebook.com
-d bbc.co.uk /modules/sharetools/
-d bigtincan.com /img/ico-b.gif
-d bigtincan.com /img/ico-in.gif
-d bufferapp.com .js
-d buzzbuttons.com
# ||buzzfeed.com^$~image,third-party
-d digg.com
-d disqus.com count.js?
# ||doubleclick.net^$domain=independent.co.uk
-d downloadatoz.com /browser_scoll.js
# ||facebook.com/connect/connect.php?id=$domain=yahoo.com
-d facebook.com /plugins/activity.php?
-d facebook.com /plugins/send.php?
-d facebook.com &pingonly=
# ||fbcdn.net^$~image,~object-subrequest,domain=~facebook.com|~jamendo.com|~skyhighmtdandenong.com.au
-d feedsportal.com /images/bookmark.
-d filehippo.com /img/b.gif
-d filehippo.com /img/fb.png
# ||filestube.com/files/images/google$image
# ||filestube.com/software/images/book_$image
-d forbes.com /home-follow.
-d gigya.com /wildfire/js/wfapiv
# ||google.com/js/plusone.js$third-party,domain=~downinfront.net|~eonline.com|~google.ca|~google.co.nz|~google.co.uk|~google.com|~google.com.au|~googlezeitgeist.com|~popularmechanics.com
# ||graph.facebook.com^$~image,third-party
-d hallamozconnect.com.au /facebook
-d icio.us /feeds/json/url/data?
-d linkedin.com
# ||linksalpha.com^$script,subdocument,third-party
-d meebo.com _100x60.
# ||microsoft.com^*_twitter$image
# ||microsoft.com^*facebook16$image
-d netdna-cdn.com /DGFacebook.
-d niftybuttons.com
-d phonesreview.co.uk /prfacebook.
-d phonesreview.co.uk /prtwitter.
-d pinit-cdn.pinterest.com
-d pinterest.com /images/about/buttons/
-d platform.foursquare.com .js
# ||platform.tumblr.com^$image,script,third-party
# ||platform.twitter.com/widgets.js$third-party,domain=~engadget.com
-d plusone.google.com /_/apps-static/
-d plusone.google.com /fastbutton?
# ||po.st^*/script/$third-party,domain=~via.me
-d punchtab.com /mast/connect?
# ||reddit.com^$third-party,domain=~reddit.tv|~scrolldit.com
# ||sharethis.com^$~script
-d slashdot.org
-d socialguide.com .js
-d socialize-it.com
-d sociallist.org
-d socialmarker.com
-d socialtwist.com
-d spiceworks.com /share/
-d static.addtoany.com
# ||stumble-upon.com^$domain=~stumbleupon.com
# ||stumbleupon.com^$script,subdocument,third-party
-d tadst.com /gfx/n/spr_
-d tinker.com
# ||tools.awe.sm^$subdocument,third-party
-d topsy.com
-d turbobit.net /files/news/folder_eng.png
-d turbobit.net /oexktl/
-d tweetboard.com
-d tweetmeme.com
-d twitbuttons.com
-d twitter.com /statuses/
-d twittercounter.com
-d twitthis.com
-d uploaded.net /img/fb.
-d virginmobile.com.au /vm-sprite.
-d wd-edge.sharethis.com /button/
-d wibiya.com
# ||widgets.awe.sm^$script,subdocument,third-party
-d widgets.dzone.com
-d widgets.getglue.com .js
# ||widgets.klout.com^$script,subdocument,third-party
# ||widgets.twimg.com^$script,domain=~services.mozilla.com|~twitter.com
-d widgetsplus.com .js
-d xing-share.com .js
#
#----- TESTING -- Will be removed if they get hits anywhere other than iGoogle -----
#
# @@||googleusercontent.com/gadgets/$xmlhttprequest,domain=googleusercontent.com,~third-party
#
#----- TESTING -- Will be removed if they get hits anywhere other than on Google services -----
#
# @@||www-*-opensocial.googleusercontent.com^$domain=googleusercontent.com|~webcache.googleusercontent.com
